#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
#
# Generate the certificates and signatures used by the PKCS#7
# selftest, and emit them as a C header on stdout. The root
# certificate is also written, in PEM format, to the file given as an
# argument, from which it is compiled in as a builtin key:
#
#   cd test/self
#   ./pkcs7-gen.sh pkcs7-root.pem >pkcs7-data.h
#   make ... REGENERATE_KEYTOC=1
#
# The output is checked in, so that building the tests does not
# depend on OpenSSL.

set -e

pem=$(realpath "$1")

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
cd "$tmp"

ossl() {
	openssl "$@" 2>/dev/null
}

cat >ext-ca.cnf <<EOF
basicConstraints = critical, CA:TRUE
keyUsage = critical, keyCertSign, digitalSignature
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
EOF

# No AuthorityKeyIdentifier, as is common with X.509v1 certificates
: >ext-none.cnf

cat >ext-leaf.cnf <<EOF
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
EOF

RSA2048="-algorithm RSA -pkeyopt rsa_keygen_bits:2048"
P256="-algorithm EC -pkeyopt ec_paramgen_curve:P-256"
P384="-algorithm EC -pkeyopt ec_paramgen_curve:P-384"

# name, keygen args
selfsigned() {
	ossl genpkey $2 -out $1.key
	ossl req -new -x509 -key $1.key -subj "/O=barebox/CN=$1" \
	     -days 3650 -sha256 -out $1.pem
}

# name, issuer, keygen args, extensions
issued() {
	ossl genpkey $3 -out $1.key
	ossl req -new -key $1.key -subj "/O=barebox/CN=$1" -out $1.csr
	ossl x509 -req -in $1.csr -CA $2.pem -CAkey $2.key \
	     -set_serial 0x$(openssl rand -hex 8) -days 3650 -sha256 \
	     -extfile $4 -out $1.pem
}

selfsigned root "$RSA2048"
cp root.pem "$pem"
issued inter root "$P256" ext-ca.cnf
issued leaf inter "$RSA2048" ext-leaf.cnf
issued leaf_ec root "$P384" ext-leaf.cnf
issued leaf_noakid root "$P256" ext-none.cnf
selfsigned rogue "$RSA2048"

printf 'barebox pkcs7 test data\n' >data

# A dm-verity root hash, signed as its hex representation
root_hash=$(printf 'barebox verity' | sha256sum | cut -d' ' -f1)
printf '%s' $root_hash >root_hash

# name, signer, extra args
sign() {
	name=$1
	signer=$2
	shift 2
	ossl cms -sign -binary -in ${IN:-data} -signer $signer.pem \
	     -inkey $signer.key -outform DER -out $name.p7s "$@"
}

# Chain included, no signed attributes (like systemd-repart)
sign sig_noattr leaf -noattr -certfile inter.pem
# Chain included, OpenSSL's default signed attributes
sign sig_attrs leaf -certfile inter.pem
# No certificates at all, signer must be trusted directly
sign sig_nocerts leaf -noattr -nocerts
# Signer identified by subjectKeyIdentifier (CMS version 3)
sign sig_keyid leaf -noattr -keyid -certfile inter.pem
# ECDSA P-384, SHA-384
sign sig_ec leaf_ec -md sha384
# Chain has to be followed by the name of the issuer
sign sig_noakid leaf_noakid
# Not issued by anyone we trust
sign sig_rogue rogue -noattr
# Two signers, one of them untrusted
ossl cms -sign -binary -in data -noattr -outform DER -out sig_multi.p7s \
     -signer rogue.pem -inkey rogue.key \
     -signer leaf.pem -inkey leaf.key -certfile inter.pem

# The root hash, like systemd-repart does it
IN=root_hash sign sig_root_hash leaf -certfile inter.pem

# Attached (embedded) content is not supported for verification of
# detached data
ossl cms -sign -binary -in data -signer leaf.pem -inkey leaf.key \
     -noattr -nodetach -outform DER -out sig_attached.p7s

emit_der() {
	echo "static const u8 $1[] = {"
	xxd -i | sed 's/^ */\t/'
	echo "};"
	echo
}

echo "/* SPDX-License-Identifier: GPL-2.0-only */"
echo "/* Generated by test/self/pkcs7-gen.sh, do not edit */"
echo
printf 'static const char data[] = "barebox pkcs7 test data\\n";\n'
printf 'static const char root_hash[] = "%s";\n' $root_hash
echo

for c in root inter leaf leaf_ec leaf_noakid rogue; do
	ossl x509 -in $c.pem -outform DER | emit_der ${c}_der
done

for s in sig_noattr sig_attrs sig_nocerts sig_keyid sig_ec sig_noakid \
	 sig_rogue sig_multi sig_attached sig_root_hash; do
	emit_der ${s} <$s.p7s
done
