#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
#
# Generate the certificates used by the X.509 selftest, and emit them
# as a C header on stdout:
#
#   test/self/x509-gen.sh >test/self/x509-certs.h
#
# The output is checked in, so that building the tests does not
# depend on OpenSSL, and so that the expected values stay stable.

set -e

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
cd "$tmp"

ossl() {
	openssl "$@" 2>/dev/null
}

# name, keygen args, cert args...
selfsigned() {
	name=$1
	shift
	keyargs=$1
	shift
	ossl genpkey $keyargs -out $name.key
	ossl req -new -x509 -key $name.key -subj "/O=barebox/CN=$name" \
	     -days 3650 "$@" -outform DER -out $name.der
}

# name, issuer, keygen args, cert args...
issued() {
	name=$1
	issuer=$2
	shift 2
	keyargs=$1
	shift
	ossl genpkey $keyargs -out $name.key
	ossl req -new -key $name.key -subj "/O=barebox/CN=$name" -out $name.csr
	ossl x509 -req -in $name.csr -CA $issuer.der -CAkey $issuer.key \
	     -set_serial 0x$(openssl rand -hex 8) -days 3650 \
	     -extfile ext-leaf.cnf "$@" -outform DER -out $name.der
}

cat >ext-leaf.cnf <<EOF
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
EOF

RSA2048="-algorithm RSA -pkeyopt rsa_keygen_bits:2048"
RSA3072="-algorithm RSA -pkeyopt rsa_keygen_bits:3072"
RSA4096="-algorithm RSA -pkeyopt rsa_keygen_bits:4096"
P256="-algorithm EC -pkeyopt ec_paramgen_curve:P-256"
P384="-algorithm EC -pkeyopt ec_paramgen_curve:P-384"

selfsigned ca_rsa "$RSA2048" -sha256
selfsigned ca_ec "$P256" -sha256
selfsigned root_rsa4096 "$RSA4096" -sha512

issued leaf_rsa ca_rsa "$RSA3072" -sha384
issued leaf_ec ca_ec "$P256" -sha256
issued leaf_ec384 ca_rsa "$P384" -sha512

# A key we support, signed with an algorithm we don't (RSA-PSS)
issued leaf_pss ca_rsa "$RSA2048" -sha256 -sigopt rsa_padding_mode:pss

# A key we don't support
selfsigned ed25519 "-algorithm ED25519"

# The same key and subject as ca_rsa, but a different serial number
ossl req -new -x509 -key ca_rsa.key -subj "/O=barebox/CN=ca_rsa" \
     -days 3650 -sha256 -set_serial 42 -outform DER -out ca_rsa_reissued.der

emit() {
	name=$1

	echo "static const u8 ${name}_der[] = {"
	xxd -i <$name.der | sed 's/^ */\t/'
	echo "};"
	echo

	spki=$(ossl x509 -inform DER -in $name.der -pubkey -noout |
		       ossl pkey -pubin -outform DER | sha256sum | cut -d' ' -f1)
	echo "static const char ${name}_spki_sha256[] = \"$spki\";"
	fpr=$(sha256sum <$name.der | cut -d' ' -f1)
	echo "static const char ${name}_fingerprint[] = \"$fpr\";"
	echo
}

echo "/* SPDX-License-Identifier: GPL-2.0-only */"
echo "/* Generated by test/self/x509-gen.sh, do not edit */"
echo

for c in ca_rsa ca_ec root_rsa4096 leaf_rsa leaf_ec leaf_ec384 \
	 leaf_pss ed25519 ca_rsa_reissued; do
	emit $c
done
